[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[headers]]
  for = "/content.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
